### ISSUE TITLE
Carousel Learn More Button gets cut off

### ISSUE THREAD

**Issue by RochX** [RochX/hornethq-2.0-integrated#38]
When a course has a long title, sometimes the learn more button gets cut off.

**Comment by RochX** [comment]
<img width="1512" alt="Screenshot 2023-11-15 at 11 23 13" src="https://github.com/RochX/hornethq-2.0-integrated/assets/44243381/7c1eea4d-6835-418e-a5b3-8d972b1dafc4">

Example screenshot

**Comment by RochX** [comment]
Current fix as of commit 2fc4493 in pull request https://github.com/RochX/hornethq-2.0-integrated/pull/37.
<img width="1512" alt="Screenshot 2023-11-15 at 11 41 56" src="https://github.com/RochX/hornethq-2.0-integrated/assets/44243381/e858d562-5e6b-43e9-8a5b-8d09bb7aef71">

**Comment by harshsepi0l** [comment]
This is fixed my changing the div container and manipulating the image's size parameters.
